# This file is auto-generated by the release workflow. Do not edit by hand.
class KojacoordProxy < Formula
  desc "High-performance Minecraft proxy"
  homepage "https://github.com/KojaCraft/kojacoord"
  version "0.1.14"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/KojaCraft/kojacoord/releases/download/v0.1.14/kojacoord-proxy-macos-aarch64"
      sha256 "467b67915ddc7f9e7b9912ee16a54cbe5299a5980595f2c5f9608c8313c86b54"
    end
    on_intel do
      url "https://github.com/KojaCraft/kojacoord/releases/download/v0.1.14/kojacoord-proxy-macos-x86_64"
      sha256 "26064b6d62d321376ec200495c5ce2440df7f6796c2478d5b5fa40ed8e42878b"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/KojaCraft/kojacoord/releases/download/v0.1.14/kojacoord-proxy-linux-aarch64"
      sha256 "19b7d40f74a4f1516c2ac6ea233a20644739d20e154efb62467c327cfaf0da2b"
    end
    on_intel do
      url "https://github.com/KojaCraft/kojacoord/releases/download/v0.1.14/kojacoord-proxy-linux-x86_64"
      sha256 "fa080b48dc968951764ad299f5be6ab993c58b8a612dd46eb26e16c268a02a2e"
    end
  end

  def install
    bin.install Dir["kojacoord-proxy-*"].first => "kojacoord-proxy"
  end

  test do
    assert_match "kojacoord", shell_output("#{bin}/kojacoord-proxy --help 2>&1", 2)
  end
end
