# This file is auto-generated by the release workflow. Do not edit by hand.
class KojacoordProxy < Formula
  desc "High-performance Minecraft proxy"
  homepage "https://github.com/aleroycz/kojacoord"
  version "0.1.7"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.7/kojacoord-proxy-macos-aarch64"
      sha256 "857f508df9441d2ae1da581a461f319ec21ddc0bf52734853379576e189aab89"
    end
    on_intel do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.7/kojacoord-proxy-macos-x86_64"
      sha256 "43a7ffda45d357d02b7453cad302e92d5b0e2de3ef08fed66b61b716b21f20c7"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.7/kojacoord-proxy-linux-aarch64"
      sha256 "767e08c116bbb3b0c851bfc2951b96e73cfacd7e75ead39e6b5de315ce023d03"
    end
    on_intel do
      url "https://github.com/aleroycz/kojacoord/releases/download/v0.1.7/kojacoord-proxy-linux-x86_64"
      sha256 "61acb92fff0cc56c897d8d314000e5c503afaacc841345d82cd39041121cee7e"
    end
  end

  def install
    bin.install Dir["kojacoord-proxy-*"].first => "kojacoord-proxy"
  end

  test do
    assert_match "kojacoord", shell_output("#{bin}/kojacoord-proxy --help 2>&1", 2)
  end
end
