# This file is auto-generated by the release workflow. Do not edit by hand.
class KojacoordProxy < Formula
  desc "High-performance Minecraft proxy"
  homepage "https://github.com/KojaCraft/kojacoord"
  version "0.1.15"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/KojaCraft/kojacoord/releases/download/v0.1.15/kojacoord-proxy-macos-aarch64"
      sha256 "200fac49c4a7b3af8781cfd5e4e15dd9d01378d801d211c02c81e6fddfb8b1ed"
    end
    on_intel do
      url "https://github.com/KojaCraft/kojacoord/releases/download/v0.1.15/kojacoord-proxy-macos-x86_64"
      sha256 "5eb14ca9bad881117c512fd59df31d90c1f294ddf3b2137b4bdb9014250bb9c4"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/KojaCraft/kojacoord/releases/download/v0.1.15/kojacoord-proxy-linux-aarch64"
      sha256 "849d76f40b3690f5691d67e275df236055e742536e6949892091d5776de4f5bd"
    end
    on_intel do
      url "https://github.com/KojaCraft/kojacoord/releases/download/v0.1.15/kojacoord-proxy-linux-x86_64"
      sha256 "2324ebdc79b7b1e57557bb8bcb086371eed958708af35f679c64bff33cf0eb6e"
    end
  end

  def install
    bin.install Dir["kojacoord-proxy-*"].first => "kojacoord-proxy"
  end

  test do
    assert_match "kojacoord", shell_output("#{bin}/kojacoord-proxy --help 2>&1", 2)
  end
end
